"""Schemas package - exports all Pydantic schemas."""
from app.schemas.user import (
    UserRegister,
    UserLogin,
    Token,
    TokenPayload,
    UserBase,
    UserResponse,
    UserUpdate,
    AddressSchema,
    CustomerProfileBase,
    CustomerProfileCreate,
    CustomerProfileUpdate,
    CustomerProfileResponse,
)
from app.schemas.handyman import (
    HandymanProfileBase,
    HandymanProfileCreate,
    HandymanProfileUpdate,
    HandymanProfileResponse,
    HandymanPublicProfile,
    VerificationDocumentCreate,
    VerificationDocumentResponse,
    VerificationReview,
    LocationUpdate,
)
from app.schemas.job import (
    JobRequestCreate,
    JobRequestUpdate,
    JobRequestResponse,
    JobRequestListResponse,
    OfferCreate,
    OfferResponse,
    OfferListResponse,
    OfferAccept,
)
from app.schemas.order import (
    OrderResponse,
    OrderStatusUpdate,
    OrderListResponse,
    PaymentIntentCreate,
    PaymentIntentResponse,
    PaymentResponse,
    PaymentConfirm,
)
from app.schemas.chat import (
    ChatMessageCreate,
    ChatMessageResponse,
    ChatThreadResponse,
    ChatThreadWithMessages,
    ChatThreadListResponse,
    WebSocketMessage,
    WebSocketEvent,
)
from app.schemas.review import (
    ReviewCreate,
    ReviewResponse,
    ReviewListResponse,
    ReviewSummary,
)

__all__ = [
    # User schemas
    "UserRegister",
    "UserLogin",
    "Token",
    "TokenPayload",
    "UserBase",
    "UserResponse",
    "UserUpdate",
    "AddressSchema",
    "CustomerProfileBase",
    "CustomerProfileCreate",
    "CustomerProfileUpdate",
    "CustomerProfileResponse",
    # Handyman schemas
    "HandymanProfileBase",
    "HandymanProfileCreate",
    "HandymanProfileUpdate",
    "HandymanProfileResponse",
    "HandymanPublicProfile",
    "VerificationDocumentCreate",
    "VerificationDocumentResponse",
    "VerificationReview",
    "LocationUpdate",
    # Job schemas
    "JobRequestCreate",
    "JobRequestUpdate",
    "JobRequestResponse",
    "JobRequestListResponse",
    "OfferCreate",
    "OfferResponse",
    "OfferListResponse",
    "OfferAccept",
    # Order schemas
    "OrderResponse",
    "OrderStatusUpdate",
    "OrderListResponse",
    "PaymentIntentCreate",
    "PaymentIntentResponse",
    "PaymentResponse",
    "PaymentConfirm",
    # Chat schemas
    "ChatMessageCreate",
    "ChatMessageResponse",
    "ChatThreadResponse",
    "ChatThreadWithMessages",
    "ChatThreadListResponse",
    "WebSocketMessage",
    "WebSocketEvent",
    # Review schemas
    "ReviewCreate",
    "ReviewResponse",
    "ReviewListResponse",
    "ReviewSummary",
]
